import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Bg from "../components/Bg";
import Projects from "../components/Projects";
import About from "../components/About";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mustafa Islamovic // HUB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/main.png" />
      </Head>
      <Hero></Hero>
      <About></About>
    </div>
  );
}
