import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
import me from '../public/me.jpg'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bgWrap flex items-center justify-center'>
        <Image src='/../public/me.jpg' 
        alt='me'
        width={350}
        height={350}
        quality={100}
        priority={true}
        />
      </div>
      <Hero></Hero>
    </div>
  )
}